server:
  port: 8899

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  file: logs/Landscape-Auth-Server.log    
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
  level:
     root: debug         
     org:
       springframework:
         security: DEBUG
             
---
spring:
  profiles: dev
  database:
    driverClassName: org.h2.Driver
  datasource:    
    url: jdbc:h2:tcp://localhost/~/landscapeDB
    username: dbuser
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: validate
 
